# @package _global_
# set:fsy
# date: 2025-6-22
# Modified from `domain_rand_base.yaml` and `pbhc/main.yaml`
domain_rand:
  # push robots
  _push_fixed: true
  push_robots : True
  push_interval_s : [5, 10]
  max_push_vel_xy : 0.1

  # base com
  randomize_base_com : True
  base_com_range: 
      x : [-0.05, 0.05]
      y : [-0.05, 0.05]
      z : [-0.01, 0.01]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.9, 1.1]

  randomize_link_inertia : True
  link_inertia_range : [0.9,1.1] # *factor
  randomize_link_inertia_names : [
      'pelvis', 'torso_link',
      'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 'left_wrist_roll_rubber_hand', 
      'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link', 'right_wrist_roll_rubber_hand',
      'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
      'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link'
  ]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.9, 1.1]
  kd_range : [0.9, 1.1]

  # friction
  randomize_friction : True
  friction_range : [0.2, 1.2]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : True
  use_rao : True
  rao_lim : 0.05
  rfi_lim : 0.05
  randomize_rfi_lim : True
  rfi_lim_range : [0.5, 1.5]


  # control delay
  randomize_ctrl_delay : True
  ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms